spring:
    application:
        name: todo-list
    datasource:
        url: jdbc:postgresql://localhost:5432/todo_db
        username: admin
        password: admin

    jpa:
        hibernate:
            ddl-auto: update
            
server:
    port: 8081